<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Test_Suite_Local_and_Global_Variables_001</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>98b19810-d3ca-44f7-b8f8-2e1e786df31f</testSuiteGuid>
   <testCaseLink>
      <guid>6a01782b-fa0b-4ca4-8b17-c6d3aea59708</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Local and Global Variables/TC_Amazon_Global_Variable</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cebb7b83-d613-4c1a-ba50-400edd7473d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b070ad16-8e35-41be-904e-c9f967dd8d6b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f51e35c9-2c75-406e-811e-cfdf417182b3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Local and Global Variables/TC_Amazon_Local_Variable</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>62c91814-75cc-4a80-9e70-7204c170347c</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Amazon_Data_Files_Excel/Amazon_TestData_Excel</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>62c91814-75cc-4a80-9e70-7204c170347c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Email</value>
         <variableId>985f7824-153f-4c15-b584-2f4e219c2665</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>62c91814-75cc-4a80-9e70-7204c170347c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>77af2edf-81c7-4112-a11d-a8bd594e6485</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
