<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Go to Cart</name>
   <tag></tag>
   <elementGuidId>ad4b38a4-887a-456d-8bf2-beaaafe30541</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sw-gtc > span.a-button-inner > a.a-button-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='sw-gtc']/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a0cdf37e-8afc-4425-aea1-29dda4136e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/cart?ref_=sw_gtc</value>
      <webElementGuid>7c8fb4dd-95f8-4564-a0f2-628aeae64061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-content-id</name>
      <type>Main</type>
      <value>sw-gtc_CONTENT</value>
      <webElementGuid>254f84b6-031b-48bb-8ad1-093face6212b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-slot-id</name>
      <type>Main</type>
      <value>sw-gtc</value>
      <webElementGuid>416facc4-5443-440a-8822-177aecc656a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>729aad40-69e5-43f0-b5a4-46910189b11d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-text</value>
      <webElementGuid>db987861-d80e-4f31-8b54-d2e04f7a7b23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>nte6dh-w5re25-8s0qk3-1webe2</value>
      <webElementGuid>e79f2865-7408-4148-b037-604fd07f1842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    Go to Cart
</value>
      <webElementGuid>14da582e-afe9-49bf-93bb-52c8e3d1adf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sw-gtc&quot;)/span[@class=&quot;a-button-inner&quot;]/a[@class=&quot;a-button-text&quot;]</value>
      <webElementGuid>75b36e64-2f4a-4ec0-9131-8936c8c362f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='sw-gtc']/span/a</value>
      <webElementGuid>25b6c882-9da0-45f9-a525-0a4507c2b39a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Go to Cart')])[2]</value>
      <webElementGuid>79e88336-981a-4143-9d7b-867e3bb50034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check out Amazon Cart'])[1]/following::a[1]</value>
      <webElementGuid>8745f4a0-e52c-4092-9f4f-95b3d34568a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sign in to your account'])[1]/preceding::a[1]</value>
      <webElementGuid>616208e8-f288-4c21-be6f-61d1e647b36b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/cart?ref_=sw_gtc')]</value>
      <webElementGuid>0a611f0a-e9d3-49ad-94b3-3cb61d9e2d44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/div/div/span/span/a</value>
      <webElementGuid>12165c02-b6d2-4dae-8969-87345167a95e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/cart?ref_=sw_gtc' and (text() = '
    Go to Cart
' or . = '
    Go to Cart
')]</value>
      <webElementGuid>85e3e4ba-386a-4e94-8d70-73556c99461d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
